version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: employees_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: employees_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      #- ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  fastapi:
    build: .
    container_name: employees_api
    restart: always
    ports:
      - "8000:8000"
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USER: admin
      DATABASE_PASSWORD: admin123
      DATABASE_NAME: employees_db
      APP_NAME: "Employees API"
      APP_VERSION: "1.0.0"
      DEBUG: "True"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app_network
    volumes:
      - ./app:/app/app

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge